export const SUGGESTED_NAMES = [
    'Wallace',
    'Warley',
    'Warlen',
    'Welton',
    'Waldemar',
    'Waldir',
    'Waldo',
    'Waldomiro',
    'Walgi',
    'Walter',
    'Walmor',
    'Walson',
    'Waldisnei',
    'Walisson',
    'Walton',
    'Walssomar',
    'Waldinei',
    'Walgismar',
    'Wander',
    'Wagner',
    'Wanderson',
    'Washington',
    'Wanderley',
    'Wandaley',
    'Wady',
    'Walton',
    'Waldrich',
    'Walger',
    'Waltrode',
    'Walison',
    'Wallis',
    'Wayne'
];

export const SLACK_WEBHOOK = 'https://hooks.slack.com/services/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';